- name : install tuned elastic profile
  ansible.builtin.copy:
    src: tuned-elastic.conf
    dest: /usr/lib/tuned/elastic/tuned.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  tags:
    - tuned
    - elastic

- name: activate elastic tuned profile
  ansible.builtin.shell: sudo tuned-adm profile elastic
  become: true
  tags:
    - tuned
    - elastic
